config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :categories


  resources :listings
  namespace :listings do
  	namespace :rentals do
  		resources :listings
  	end
  end

  authenticated :user do
    root :to => 'listings#index'
  end
  root :to => "listings#index"
  devise_for :users
  resources :users
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :bedrooms, :address, :category_id, :city, :country, :description, :email, :featured, :phone, :price, :source, :spam, :state, :title, :url, :zipcode

  has_many :custom_attributes, :foreign_key => :owner_id

  belongs_to :user
  belongs_to :category

  geocoded_by :full_address
  after_validation :geocode, :populate_address_fields

  validates :price, presence: true
  validates :title, presence: true
  validates :image_url, presence: true

  searchable do
    text :title, :default_boost => 2
    text :city
    text :state
    text :description
    double :price
    double :bedrooms
    double :sqrft
  end

  def full_address
    [address, city, state, zipcode, country].compact.join(" ")
  end

  private

  def populate_address_fields
    geocode_result = Geocoder.search(full_address)
    unless geocode_result.empty?
      first_address = geocode_result.first
      self.address = first_address.address
      self.city    = first_address.city
      self.state   = first_address.state
      self.zipcode = first_address.postal_code
      self.country = first_address.country
    end
  end
end

app/controllers/listings/rentals/listings_controller.rb
class Listings::Rentals::ListingsController < ListingsController
	def index
		@listings = rentals_category.listings.paginate(:per_page => 25, :page => params[:page])
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index,:show]

  # GET /listings
  # GET /listings.json
  def index
    if params[:q] || params[:filter]
      @search = Listing.search do
        paginate :page => params[:page], :per_page => 25
        keywords(params[:q])
        any_of do
          if params[:price].present?
            with(:price, Range.new( params[:price].split("-").first, params[:price].split("-").last))
          end

          if params[:bedrooms].present?
            with(:bedrooms, Range.new( params[:bedrooms].split("-").first, params[:bedrooms].split("-").last))
          end

          if params[:square_footage].present?
            with(:sqrft, Range.new( params[:square_footage].split("-").first, params[:square_footage].split("-").last))
          end
        end

      end
      @listings = @search.results
    else
      @listings = Listing.paginate(:per_page => 25, :page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    params[:q] = @listing.city.to_s

    @search = Listing.search do
      keywords( params[:q] )
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = current_user.listings.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = current_user.listings.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = current_user.listings.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/shared/_index.html.erb
<ul id='listings'>
    <% @listings.each do |listing| %>
    <li>
    	<div class='row well'>
    		<div class='span2'>
    			<%= link_to image_tag(listing.image_url, :"data-src" => '/assets/holder.js?100x100', class: 'thumbnail img-rounded', style: 'width: 180px; height: 150px; margin: 10px'), [:listings,:rentals,listing] %>
    		</div>
    		<div class='span6'>
        	<h4><%= link_to listing.title.truncate(40), [:listings,:rentals,listing], target: '_blank' %></h4>
        	<span class='bigprice'><%= number_to_currency listing.price %></span>
            <br />
            Posted By: <%= listing.user ? listing.user.name : 'Zuminati' %>
            <br />
            <%= listing.full_address %>
            <br />
            Bedrooms: <%= listing.bedrooms.to_i %>
            <br />
            SQRFT: <%= listing.sqrft %>
            <br />
            Phone: <%= number_to_phone listing.phone %>
            <br />
            <%= link_to 'View Original', listing.url, target: '_blank', class: 'btn btn-small' %>
        </div>
       </div>
    </li>
    <% end %>
</ul>

<%= will_paginate @listings %>

app/views/listings/shared/_range_select.html.erb
<div>
	<label for='price'><%= field.titleize %>:</label><span id='<%= field %>_label'></span>
</div>
<br />
<div id='<%= field %>_slider'></div>
<input type='hidden' name='<%= field %>' id='<%= field %>' value="<%= params[field.to_sym] %>" />
<% content_for :head do %>
	<script>
		$(function() {
	        $( "#<%= field %>_slider" ).slider({
	        	min: <%= min %>,
	        	max: <%= max %>,
	        	range: <%= range %>,
	        	values: <%= values %>,
	        	slide: function( event, ui ) {
	        		label = "<%= price ? '$' : '' %>";
	          	$( "#<%= field %>_label" ).html( label + ui.values[0] + " - " + label + ui.values[1] );
	          	$('input#<%= field %>').val(ui.values[0] + "-" + ui.values[1]);

	          }
	        })
	        $( "#<%= field %>_label" ).html("<%= min %> - <%= max %>");
	    });
	 </script>
<% end %>

app/views/listings/shared/_show.html.erb
<p id="notice"><%= notice %></p>

<div class='row well'>
  <div class='span10'>
    <h2><%= listing.title %></h2>
  </div>
  <div class='span2'>
    <%= image_tag(listing.image_url, class: 'thumbnail', alt: listing.title, title: listing.title) %>

    <%= link_to 'View Original Listing', listing.url, target: '_blank', class: 'btn btn-mini' %>

    <div class='well'>
      <span class='price'><%= number_to_currency listing.price %></span>
      
      <p>
       <%= listing.address %>
       <%= listing.city %>, <%= listing.state %>
       <%= listing.zipcode %> <%= listing.country %>
      </p>

      <p>
        <b>Phone:</b>
        <%= listing.phone %>
      </p>

      <p>
        <b>Email:</b>
        <%= listing.email %>
      </p>


    </div>
  </div>
  <div class='span6'>
    <p>
      <%= listing.description.html_safe %>
    </p>

    <%= link_to 'Edit', edit_listings_rentals_listing_path(listing) if current_user && current_user.listings.include?(listing) %>
  </div>
  <div class='span6 well row'>
    <h4>Similar Listings</h4>
    
    <% @search.results[0..4].each do |list| %>
      <div class='span1'><%= link_to image_tag(list.image_url, style: 'width: 60px; height: 60px;', class: 'thumbnail', alt: list.title, title: list.title), list %><br />
        <%= link_to list.title.truncate(20), list %><br /> <%= number_to_currency list.price %></div>
    <% end if @search %>
    
  </div>
</div>

<div id="preview-modal" class="modal hide">
    <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h3><%= listing.title.truncate(30) %></h3>
    </div>
    <div class="modal-body">
        <%= image_tag listing.image_url %>
    </div>
    <div class="modal-footer">
        <a href="javascript:$('#preview-modal').modal('hide');" class="btn">Close</a>
    </div>
</div>

<script>
  $(document).ready(function(){
    $('#preview-modal').modal('hide');
    $('.thumbnail').click(function(){
      $('#preview-modal').modal('show');
    });
  });
</script>

app/views/listings/shared/_sidebar.html.erb
<%
price = params[:price] ?  params[:price].split("-") : [1,100000]
bedrooms = params[:bedrooms] ?  params[:bedrooms].split("-") : [1,10]
sqrft = params[:square_footage] ? params[:square_footage].split("-") : [1,100000]
%>
<div class='well'>
<form action='/listings' method='get'>
<ul>
	<li>
		<%= render 'listings/shared/range_select', field: 'price', values: raw(price), min: 1, max: 100000000, range: true, price: true %>
	</li>
	<li>
		<%= render 'listings/shared/range_select', field: 'bedrooms', values: raw(bedrooms), range: true, price: false, min: 1, max: 10 %>
	</li>
	<li>
		<%= render 'listings/shared/range_select', field: 'square_footage', values: raw(sqrft), value: "100 - 10000", min: 1, max: 10000, range: true, price: false, min: 100, max: 8000 %>
	</li>
</ul>
<input type='hidden' name='filter' value='true' />
<input type='submit' value='Update' class='btn btn-primary' />
</form>
</div>