config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :categories


  resources :listings
  namespace :listings do
  	namespace :rentals do
  		resources :listings
  	end
  end

  authenticated :user do
    root :to => 'listings#index'
  end
  root :to => "listings#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Zuminati", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to "Homes For Rent", listings_rentals_listings_path %>
  </li>
  <li>
    <%= link_to 'Add a listing', new_listing_path %>
  </li>
  <li>
    <form action="/listings" class='inline'>
      <input type="text" class="input-small search-query span3" name='q' value="<%= params[:q] %>" />
      <button type="submit" class="btn btn-small">Search</button>
    </form>
  </li>
    <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Your Account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Zuminati - Online Classifieds Simplified" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Zuminati - Online Classifieds Simplified" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/themes/base/jquery-ui.css" type="text/css" media="all" />
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <aside class="span2">
              <%= yield(:sidebar) %>
            </aside>
            <div class='span1'></div>
            <div class="span9">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <script>
    $(document).ready(function(){
      $('.pagination a').addClass('btn');
      $('.pagination em.current').addClass('btn btn-primary');
    });
    </script>
  </body>
</html>